version: '2'
services:
    daspanel-mail-catcher:
        build:
            context: .
            dockerfile: Dockerfile
        image: daspanel/mailhog-mail-catcher
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        ports:
            - "1025:1025"
            - "8025:8025"
        env_file:
            - daspanel.env
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


