#!/usr/bin/with-contenv sh

case "$DASPANEL_WAIT_FOR_API" in
    YES|yes|Yes)
        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
        result=$?
        if [ ! $result -eq 0 ] ; then
            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
            exit 1
        fi
        ;;
    *) 
        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
        exit 1
        ;;
esac

# Get system configs from API server and set env variables
SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
result=$?
if [ ! $result -eq 0 ] ; then
    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
    exit 1
fi
export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /usr/bin/jq -r '.sys.hostname'`

#HOSTNAME=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.hostname'`

exec su-exec daspanel:daspanel /usr/bin/mailhog \
    -auth-file=/etc/daspanel/mailhog/auth.db \
    -hostname $DASPANEL_SYS_HOSTNAME > /dev/null 2>&1
